# Generated by Django 5.0.7 on 2024-08-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideaVaultApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
