# Generated by Django 5.0.7 on 2024-08-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideaVaultApi', '0002_alter_idea_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
